void throw_exception() {
    throw "An exception occurred!";
}